### ISSUE TITLE
Broken `require_player_movement`

### ISSUE THREAD

**Issue by icecoldtofu** [Auroriax/PuzzleScript#2]
746e37622970ad5f870db38a35ede9c8a982cebe broke `require_player_movement`, can't push crates.

ed6d8ca70fbbd7718c793a0b0a30578dce1189a5 broke it even more, can't move at all.

https://auroriax.github.io/PuzzleScript/editor.html?hack=4ab055be3ff003e017ec488397c9bbb3

**Comment by Auroriax** [comment]
Very curious behavior, thanks for reporting it! I have no idea what's going wrong here but it definitely has something to do with the local_radius changes. I'll look into it.

**Comment by Auroriax** [comment]
Should be fixed in https://github.com/Auroriax/PuzzleScript/commit/429c41bec8d59c1868e223da2e7f08aff4549e5d. The engine was checking the player positions at the start of the turn, but my added code sometimes updated that during the turn, causing player position to be incorrectly compared during the required movement check. 
Thank you for listing the commits and linking a project, that made it very easy to find the bug!
